### ISSUE TITLE
To much inline styling :(

### ISSUE THREAD

**Issue by gosoccerboy5** [The64thCucumber/fdreerf.com#2]
A lot of the inline style attributes are really similar, so you could make some CSS rules for those. If you're willing to go above and beyond, you could use classes, or even create a whole stylesheet

**Comment by CodeGuy92** [comment]
![123](https://user-images.githubusercontent.com/79767244/118863595-c3fc9a80-b8e7-11eb-998e-3a7844ddcc81.PNG)

**Comment by gosoccerboy5** [comment]
> ![123](https://user-images.githubusercontent.com/79767244/118863595-c3fc9a80-b8e7-11eb-998e-3a7844ddcc81.PNG)

Oh good. I can help @The64thCucumber if he needs any. Just ping me
